language: php

php:
  - 5.3

before_script:
  - sudo apt-get -y install nodejs npm phantomjs
  - node --version
  - npm --version
  - npm install -g karma grunt-cli
  - cd utils
  - npm install .
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phing build

